# Generated by Django 5.2.9 on 2026-03-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('WEB', 'Web Development'), ('MOBILE', 'Mobile Development'), ('DESIGN', 'Design'), ('WRITING', 'Writing'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], default='WEB', max_length=20)),
                ('required_skills', models.TextField(help_text='Comma separated skills')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
